<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					<?php  if($this->view->info_user): 
						$info = $this->view->info_user[0]; ?>
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?= $info['nome'] ?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?= $info['tweets'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $info['seguindo'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $info['seguidores'] ?></span>
						</div>

					</div>
					<?php  endif; ?>
				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="POST" action="/tweet">
						<textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="tweet"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>
						
						<? if($this->view->login == 'erro'): ?>	
						<div class="row">
							<div class="col"><span class="text text-danger">*Tweet naõ deve ser vazio!</span></div>
						</div>
						<? endif; ?>
					</form>
				</div>
			</div>
			
			<?php foreach($this->view->tweets as $tweet): ?>
			<div class="row tweet">
				<div class="col">
					<p><strong><?= $tweet['nome'] ?></strong>  <small><span class="text text-muted">- <?= $tweet['data'] ?></span></small></p>
					<p><?= $tweet['tweet'] ?></p>

					<br />
					<?php if($tweet['id_usuario'] == $_SESSION['id']): ?>
					<form method="POST" action="/remover">
						<div class="col d-flex justify-content-end">
							<button type="submit" class="btn btn-danger"><small>Remover</small></button>
							<input type="hidden" name="id_tweet" value="<?= $tweet['id'] ?>">
						</div>
					</form>
					<?php endif; ?>
				</div>
			</div>
			<?php endforeach; ?>
			<div class="row mt-5 d-flex justify-content-center">
				<nav aria-label="...">
				<ul class="pagination">
					<li class="page-item">
					<a class="page-link" href="?pagina=1" tabindex="-1">Primeira</a>
					</li>
					<?php for($i=1; $i <= $this->view->total_paginas; $i++): ?>
					<li class="page-item">
					<a class="page-link" href="?pagina=<?=$i?>"><?=$i?><span class="sr-only"></span></a>
					</li>
					<?php endfor; ?>
					<li class="page-item">
					<a class="page-link" href="?pagina=<?=$this->view->total_paginas?>">Última</a>
					</li>
				</ul>
				</nav>
			</div>
		
		</div>
		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/wfollow" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>